export const contentData = [
  {
    heading: "A primer: the game of Carcassonne",
    caption: "An image of someone's Carcassonne board.",
  },
  {
    heading: "Rules of Carcassonne",
    caption: "Roads must match roads, towns for towns, and grass for grass. You can place tiles only beside already placed tiles."
  },
  {
    heading: "Random generation and Carcassonne",
    caption: "Note that in the following empty space, there are multiple types of tiles that could be placed legally.",
  },
  {
    heading: "Nethack: the first \"Procedurally Generated\" Game",
    caption: "Nethack being played on a terminal. The '@' sign represents the player.",
  },
  {
    heading: "Nethack's procedural generation system",
    caption: "A simple dungeon layout",
  },
  {
    heading: "Dwarf Fortress: the world's most complex game",
    caption: "A 'cavern' in Dwarf Fortress. Almost everything that you see is procedurally generated: the walls of the cave, the trees, the mushrooms.. even the water level is procedurally generated beforehand. Only the Dwarven rooms are made by the player.",
  },
  {
    heading: "Perlin noise: Procedural generation in DwarFort's 3D world",
    caption: "A randomly-generated world in Dwarf Fortress. The shape of this continent (and the islands beside it) are all generated through complex geometric functions that control properties like size, shape, roughness, texture (grasslands, mountains, rivers), and so much more.",
  },
  {
    heading: "What can Perlin Noise do?",
    caption: "Random b/w white noise. This is widely used as the starting point in techniques like Perlin Noise.",
    caption: "A b/w simulation of perlin noise. Notice how the darker regions overlap smoothly with the lighter regions",
    caption: "Mountains and valleys generated by Perlin noise. Larger values at certain points are converted into greater heights, and vice versa.",
  },
  {
    heading: "Trees in computer graphics: introducing L-systems",
    caption: "Some organic-looking trees generated from different L-system rules",
    caption: "[Insert interesting use-case for L-systems]"
  },
  {
    heading: "Rules of a simple L-system",
    caption: "A simple stem with 2 branches and 4 sub-branches. Each branch spawns two children branches at +45deg and -45deg angles to the main, with half the length of the parent.",
    caption: "Continuation of the pattern to another level",
    caption: "7 Levels of the fractal-like tree",
  },
  {
    heading: "[Insert game or some use-case that uses cellular automata for procedural generation]",
  },
  {
    heading: "Cellular automata: complexity from simplicity",
    caption: "Complex evolution of a system derived from 8 simple rules. The ruleset takes up just 3 bytes (0.003KB) and yet results in this chaotic pattern that's hard to predict.",
  },
  {
    heading: "Procedural Generation in media: Minecraft",
    caption: "A standard scenery from Minecraft. Even the placement of the houses in the village (and the village on the map) is decided at random by the machine, but following some base rules. Except the blue sky, everything you see is procedurally generated.",
    caption: "A top view of some Minecraft terrain. The procedural generation engine makes sure biomes are internally consistent",
  },
  {
    heading: "Procedural Generation in media: No man's sky",
    caption: "A poster for the game",
    caption: "A bunch of biomes you could end up encountering in the various planets of the game",
  },
  {
    heading: "Procedural Generation in media: Terraria",
    caption: "Some of the procedurally generated terrain of Terraria. The trees are intelligently spawned where there is greater incidence of sunlight.",
    caption: "A very zoomed-out image of a randomly-generated world in Terraria. Some features are chosen quite deliberately, like the diagonal bands of biomes in the middle, and the line of magma underneath. Some other features are more random, like the numerous spots in every biome where a second biome appears.",
  },
  {
    heading: "Procedural Generation in media: Stardew valley",
    caption: "A cave in Stardew Valley. Even such a hand-crafted world generates the cave rocks at random - simply because the human effort is not worth it.",
    caption: "This expansion mod would not have been possible without procedural generation.",
  },
  {
    heading: "World generation in DwarFort: Civilisations",
    caption: "The world creation menu. You can generate a thousand years of history simulating hundreds of empires, nations, societies, and tribes with enough lore to fill a real-life novel. All of this is procedurally generated, down to the smallest phrase or historical event.",
  },
  {
    heading: "World generation in DwarFort: Stories and Histories",
    caption: "A long, complex gameplay-story that has clearly been going on for some time.",
  },
  {
    heading: "Beyond gaming: A society simulation",
    caption: "The framework for the society simulator discussed in the paper.",
  },
  {
    heading: "To summarise..",
  },
  {
    heading: "In conclusion..",
  },
];